name: Backport-o-Matic Epoxy

on:
  # schedule:
  #   - cron: '0 */10 * * *'
  workflow_dispatch:

jobs:
  backport-epoxy:
    uses: ./.github/workflows/backport-o-matic.yaml
    with:
      release: epoxy
      series: noble
